export const LIST_PRODUCTS_USE_CASE = Symbol('LIST_PRODUCTS_USE_CASE');
export const CREATE_TRANSACTION_USE_CASE = Symbol(
  'CREATE_TRANSACTION_USE_CASE',
);
export const PROCESS_PAYMENT_USE_CASE = Symbol('PROCESS_PAYMENT_USE_CASE');
export const GET_TRANSACTION_STATUS_USE_CASE = Symbol(
  'GET_TRANSACTION_STATUS_USE_CASE',
);
